# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 259)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo/KakaoTalk_20231229_172139171_01.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: #f5f5f5;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Delete = QtWidgets.QPushButton(self.centralwidget)
        self.Delete.setGeometry(QtCore.QRect(37, 103, 281, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Delete.sizePolicy().hasHeightForWidth())
        self.Delete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Spoqa Han Sans Neo Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete.setFont(font)
        self.Delete.setStyleSheet("background-color: black;\n"
"border-radius: 5px;\n"
"color : white;")
        self.Delete.setObjectName("Delete")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(38, 155, 314, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Spoqa Han Sans Neo")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:red;")
        self.label_9.setObjectName("label_9")
        self.ButtonAdd = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonAdd.setGeometry(QtCore.QRect(-1, 1, 85, 28))
        self.ButtonAdd.setObjectName("ButtonAdd")
        self.ButtonSetting = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSetting.setGeometry(QtCore.QRect(178, 1, 76, 28))
        self.ButtonSetting.setObjectName("ButtonSetting")
        self.ButtonDelete = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonDelete.setGeometry(QtCore.QRect(84, 1, 93, 28))
        self.ButtonDelete.setObjectName("ButtonDelete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "서로이웃 추가 자동화 봇 -삭제창"))
        self.Delete.setText(_translate("MainWindow", "이웃 요청 삭제"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">더이상 서로이웃 요청을 보내기<br/> 어려울 경우에 사용하시는 것을 권장합니다.</span></p></body></html>"))
        self.ButtonAdd.setText(_translate("MainWindow", "이웃 추가"))
        self.ButtonSetting.setText(_translate("MainWindow", "설정"))
        self.ButtonDelete.setText(_translate("MainWindow", "이웃 삭제"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
