# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DeleteUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 259)
        MainWindow.setStyleSheet("background-color: #f5f5f5;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-2, -3, 258, 21))
        self.tabWidget.setBaseSize(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setFamily("Spoqa Han Sans Neo")
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color:#C0C0C0;")
        self.tabWidget.setIconSize(QtCore.QSize(50, 50))
        self.tabWidget.setObjectName("tabWidget")
        self.TabAdd_2 = QtWidgets.QWidget()
        self.TabAdd_2.setObjectName("TabAdd_2")
        self.tabWidget.addTab(self.TabAdd_2, "")
        self.TabDelete_2 = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabDelete_2.sizePolicy().hasHeightForWidth())
        self.TabDelete_2.setSizePolicy(sizePolicy)
        self.TabDelete_2.setObjectName("TabDelete_2")
        self.tabWidget.addTab(self.TabDelete_2, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.AddFriendBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddFriendBtn.setGeometry(QtCore.QRect(37, 103, 281, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFriendBtn.sizePolicy().hasHeightForWidth())
        self.AddFriendBtn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Spoqa Han Sans Neo Bold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AddFriendBtn.setFont(font)
        self.AddFriendBtn.setStyleSheet("background-color: black;\n"
"border-radius: 5px;\n"
"color : white;")
        self.AddFriendBtn.setObjectName("AddFriendBtn")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(38, 155, 314, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Spoqa Han Sans Neo")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:red;")
        self.label_9.setObjectName("label_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabAdd_2), _translate("MainWindow", "이웃 추가"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabDelete_2), _translate("MainWindow", "이웃 삭제"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "   설정   "))
        self.AddFriendBtn.setText(_translate("MainWindow", "이웃 요청 삭제"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">더이상 서로이웃 요청을 보내기<br/> 어려울 때에만 사용하시는 것을 권장합니다.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
