# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(457, 610)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.StartBtn = QtWidgets.QPushButton(Dialog)
        self.StartBtn.setGeometry(QtCore.QRect(70, 460, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.StartBtn.setFont(font)
        self.StartBtn.setStyleSheet("background-color: #ff0000;border: 2px solid red;")
        self.StartBtn.setObjectName("StartBtn")
        self.ID = QtWidgets.QLineEdit(Dialog)
        self.ID.setGeometry(QtCore.QRect(210, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.ID.setFont(font)
        self.ID.setObjectName("ID")
        self.PW = QtWidgets.QLineEdit(Dialog)
        self.PW.setGeometry(QtCore.QRect(210, 390, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.PW.setFont(font)
        self.PW.setObjectName("PW")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(70, 340, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(70, 390, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.LoginResult = QtWidgets.QLabel(Dialog)
        self.LoginResult.setGeometry(QtCore.QRect(120, 440, 261, 16))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.LoginResult.setFont(font)
        self.LoginResult.setText("")
        self.LoginResult.setObjectName("LoginResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.StartBtn.setText(_translate("Dialog", "로그인"))
        self.label_6.setText(_translate("Dialog", "아이디"))
        self.label_7.setText(_translate("Dialog", "비밀번호"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
