# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(751, 656)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 80, 271, 16))
        self.label.setObjectName("label")
        self.KeyWord = QtWidgets.QLineEdit(Dialog)
        self.KeyWord.setGeometry(QtCore.QRect(140, 30, 201, 41))
        self.KeyWord.setStyleSheet("border: 1px solid black;")
        self.KeyWord.setText("")
        self.KeyWord.setObjectName("KeyWord")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 40, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 160, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Count = QtWidgets.QLineEdit(Dialog)
        self.Count.setGeometry(QtCore.QRect(140, 150, 201, 41))
        self.Count.setStyleSheet("border: 1px solid black;")
        self.Count.setText("")
        self.Count.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Count.setObjectName("Count")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 200, 271, 16))
        self.label_4.setObjectName("label_4")
        self.CollectStatus = QtWidgets.QTextEdit(Dialog)
        self.CollectStatus.setGeometry(QtCore.QRect(50, 350, 301, 261))
        self.CollectStatus.setStyleSheet("border: 1px solid black;")
        self.CollectStatus.setMarkdown("")
        self.CollectStatus.setObjectName("CollectStatus")
        self.Id = QtWidgets.QLineEdit(Dialog)
        self.Id.setGeometry(QtCore.QRect(520, 120, 161, 21))
        self.Id.setStyleSheet("border: 1px solid black;")
        self.Id.setObjectName("Id")
        self.IdCollectBtn = QtWidgets.QPushButton(Dialog)
        self.IdCollectBtn.setGeometry(QtCore.QRect(50, 270, 301, 51))
        self.IdCollectBtn.setStyleSheet("border: 1px solid black;")
        self.IdCollectBtn.setObjectName("IdCollectBtn")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(370, 30, 21, 571))
        self.line.setAutoFillBackground(False)
        self.line.setLocale(QtCore.QLocale(QtCore.QLocale.Korean, QtCore.QLocale.SouthKorea))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Pw = QtWidgets.QLineEdit(Dialog)
        self.Pw.setGeometry(QtCore.QRect(520, 160, 161, 21))
        self.Pw.setStyleSheet("border: 1px solid black;")
        self.Pw.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pw.setObjectName("Pw")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(420, 130, 64, 15))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(420, 160, 64, 15))
        self.label_6.setObjectName("label_6")
        self.CollectStatus2 = QtWidgets.QTextEdit(Dialog)
        self.CollectStatus2.setGeometry(QtCore.QRect(420, 350, 311, 261))
        self.CollectStatus2.setStyleSheet("border: 1px solid black;")
        self.CollectStatus2.setMarkdown("")
        self.CollectStatus2.setObjectName("CollectStatus2")
        self.AddFriendBtn = QtWidgets.QPushButton(Dialog)
        self.AddFriendBtn.setGeometry(QtCore.QRect(420, 270, 311, 51))
        self.AddFriendBtn.setStyleSheet("border: 1px solid black;")
        self.AddFriendBtn.setObjectName("AddFriendBtn")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(420, 60, 211, 20))
        self.label_7.setObjectName("label_7")
        self.Rest = QtWidgets.QLabel(Dialog)
        self.Rest.setGeometry(QtCore.QRect(640, 60, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.Rest.setFont(font)
        self.Rest.setObjectName("Rest")
        self.message = QtWidgets.QLineEdit(Dialog)
        self.message.setGeometry(QtCore.QRect(420, 210, 311, 51))
        self.message.setAutoFillBackground(False)
        self.message.setStyleSheet("border: 1px solid black;")
        self.message.setInputMask("")
        self.message.setText("")
        self.message.setObjectName("message")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(60, 100, 241, 16))
        self.label_8.setStyleSheet("color: red;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(60, 220, 241, 16))
        self.label_9.setStyleSheet("color:red;")
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "서이추 봇"))
        self.label.setText(_translate("Dialog", "해당 키워드로 아이디를 수집합니다."))
        self.label_2.setText(_translate("Dialog", "키워드:"))
        self.label_3.setText(_translate("Dialog", "개수:"))
        self.label_4.setText(_translate("Dialog", "해당 개수만큼 아이디를 수집합니다."))
        self.CollectStatus.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CollectStatus.setPlaceholderText(_translate("Dialog", "현재 수집한 아이디 개수 : 0개"))
        self.IdCollectBtn.setText(_translate("Dialog", "아이디 수집 시작"))
        self.label_5.setText(_translate("Dialog", "아이디"))
        self.label_6.setText(_translate("Dialog", "비밀번호"))
        self.CollectStatus2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CollectStatus2.setPlaceholderText(_translate("Dialog", "현재 보낸 서로이웃 요청 수 : 0개"))
        self.AddFriendBtn.setText(_translate("Dialog", "서로 이웃 추가"))
        self.label_7.setText(_translate("Dialog", "중복 제거후 남은 아이디 수:"))
        self.Rest.setText(_translate("Dialog", "0"))
        self.message.setPlaceholderText(_translate("Dialog", "서로이웃 신청 메세지를 입력해주세요"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt;\">키워드는 하나만 입력해주세요</span></p></body></html>"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:7pt;\">1개당 30개의 아이디를 가져옵니다.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
